### ISSUE TITLE
Missing src package on pypi

### ISSUE THREAD

**Issue by frivoire** [aws/aws-xray-sdk-python#1]
Hello,

I've looked at : https://pypi.python.org/simple/aws-xray-sdk/
And currently, there is :
```
aws-xray-sdk-0.91.tar.gz
aws_xray_sdk-0.91.1-py2.py3-none-any.whl
aws_xray_sdk-0.92-py2.py3-none-any.whl
aws_xray_sdk-0.92.1-py2.py3-none-any.whl
aws_xray_sdk-0.92.2-py2.py3-none-any.whl
aws_xray_sdk-0.93-py2.py3-none-any.whl
```

Could you publish both the source (tar.gz) and wheel for all versions ?
Thanks in advance.

**Comment by haotianw465** [comment]
We did some repo migration during open source process and we try to avoid publish anything from the old internal repo since this GitHub repo should be the single source now. We have published 0.93 tar.gz and will publish both wheel and source in any future versions. 

Please let us know if this doesn't solve your problem.

**Comment by frivoire** [comment]
Seems good for me, and will check more precisely on monday.
To be precise, my request of "for all versions" was not really about old versions, but I was more thinking about the habit of publishing both (so for current and futures versions). So it should be ok for now on.

Thanks for the quick answer !

**Comment by haotianw465** [comment]
Sure thanks for the valuable feedback!
