### ISSUE TITLE
How to mock @xray_recorder.capture ?

### ISSUE THREAD

**Issue by gregkonushev-okta** [aws/aws-xray-sdk-python#107]
I have been trying to mock this decorator on my tests to have xray_recorder disabled while I am doing my tests. However I failed at all attempts to mock out this function. Is there any recommendation or example for this use case? How do I disable xray_recorder completely in my test runs?

**Comment by haotianw465** [comment]
We do have a backlog feature for disable X-Ray when users want to only test user code https://github.com/aws/aws-xray-sdk-python/issues/26. What is the issue you are hitting with the decorator in your test run?

**Comment by gregkonushev-okta** [comment]
I am using pytest and mock from unittest library and I am trying to mock out decorators @patch('aws_xray_sdk.core.xray_recorder.capture') like this. But then it throws exception SegmentNotFoundException

**Comment by gregkonushev-okta** [comment]
so there is workaround that I use to assign an empty class to capture method which is not ideal.

**Comment by haotianw465** [comment]
You are right. Or you can set environment variable `AWS_XRAY_CONTEXT_MISSING` to `LOG_ERROR` so no individual capture throw any error.

Ideally the SDK should have two testing modes. In one mode it should go through as much code path as possible since what will be running on production should be tested (but still should handle context missing well since most of the unit test would have no tracing context). In the other mode the SDK should go through as less code path as possible when user really just want to test the user code with completely isolating X-Ray SDK code path.

I'm closing this issue right now and please share any additional thoughts here https://github.com/aws/aws-xray-sdk-python/issues/26 so we have a single place to track all feedback and the progress.
