### ISSUE TITLE
PIP 0.94 missing Aiohttp Enhancement

### ISSUE THREAD

**Issue by ezeasharma** [aws/aws-xray-sdk-python#12]
I installed 0.94 using pip and its missing all the AioHttp enhancement
screenshot of the compat.py code installed
![image](https://user-images.githubusercontent.com/13368270/33737479-3a8ecf02-db64-11e7-8437-1eff8471e35d.png)

**Comment by haotianw465** [comment]
Sorry for the confusion. The newest version is not released yet due to some internal development planning. What's in 0.94 is the aiohttp middleware. The changes on 0.94 is here https://github.com/aws/aws-xray-sdk-python/pull/3/commits/9672b139ff45b85910eab5a6e8b6d3872388b66a

Could you tell me which Aiohttp enhancement you are looking for?

**Comment by ezeasharma** [comment]
Thanks for the quick response!
I am interested in async segment capture as provided here
https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/async_recorder.py

i don't see this module in 0.94

**Comment by haotianw465** [comment]
This will be included on the coming release. We will try to get it out as soon as possible. I'm resolving this issue for now. Thank you for your patience!
