### ISSUE TITLE
Poller threads block main thread from exiting

### ISSUE THREAD

**Issue by bendog** [aws/aws-xray-sdk-python#134]
My script appeared to be completing all of it's steps, but wouldn't exit.
I set logging to debug and it appears that aws-xray-sdk is preventing the script from exiting.
It continuously logs this line forever.
`target_poller.py->_do_work:36 - DEBUG - There is no sampling rule statistics to report. Skipping`

I'm assuming there is something wrong with the config of my system as the aws xray console doesn't appear to have any traces showing up, however this still feels like a bug to me.

using: `aws-xray-sdk==2.3.0`
on EC2 (ubuntu 18.04) with `AWS X-Ray daemon version: 3.0.0`

**Comment by bendog** [comment]
adding sampling=False resolved this.

```xray_recorder.configure(
    # daemon_address='127.0.0.1:2000',
    sampling=False,
    service=f'sms_eventhandler-{settings.ENVIRONMENT}',
    plugins=('EC2Plugin',)
)```

**Comment by chanchiem** [comment]
Hey it looks like this issue is happening because the poller is having trouble obtaining your centralized sampling rules set in the X-Ray console. When you disabled sampling, the target poller was never actually started. The design of the target poller is to use a separate thread to do its work. The reason why it was stalling is because this separate thread was active in a spin loop to poll the service for sampling rules. In the case of disabling, the thread was never created so exiting was done gracefully

The reason it would log the issue you were having is because it was unable to obtain the sampling rules from the service. Do you have it configured through your console? Please refer here on how to configure it: https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html

**Comment by bendog** [comment]
I've only got the default catch-all sampling rule configured, I had assumed this should catch it.
Perhaps the Daemon I have running on the local ec2 instance can't access those rules, I might need to look into my IAM role access.

**Comment by bendog** [comment]
I've updated my install script for xray daemon to sepecifically add the `Region: "ap-southeast-1"` entry to `/etc/amazon/xray/cfg.yaml`.
This seems to be at least get my events showing up in the xray console, I did previously have `AWS_DEFAULT_REGION=ap-southeast-1` in `/etc/environment` however it looks like this wasn't part of the xray service environment... 

```bash
# XRAY
curl -o /home/ubuntu/aws-xray-daemon-3.x.deb  https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-3.x.deb
sudo dpkg -i /home/ubuntu/aws-xray-daemon-3.x.deb
sudo chown xray:xray /var/log/xray/xray.log
sudo chown -Rv xray /etc/amazon/xray
sudo sed -i 's/Region: ""/Region: "ap-southeast-1"/g' /etc/amazon/xray/cfg.yaml
sudo systemctl enable xray
sudo systemctl start xray
```

However i'm still getting the infinite loop when sampling is turned back on, so i'm not sure why it can't get my 
```python
xray_recorder.configure(
    daemon_address='127.0.0.1:2000',
    sampling=True,
    service=f'sms_eventhandler-{settings.ENVIRONMENT}',
    plugins=('EC2Plugin',)
)
xray_recorder.begin_segment(f'sms_eventhandler-{settings.ENVIRONMENT}')
patch_all()
```

**Comment by chanchiem** [comment]
Does this issue affect whether your traces are showing up on the console? Other than the infinitely running thread, are you experiencing any issues that are throwing errors and exceptions?

The target poller would write "There is no sampling rule statistics to report. Skipping" if doesn't need to report any statistics information to the service (either it had already refreshed its internal rule statistics or hasn't incremented its internal sampling quota because no segment/subsegment has been sent out since the last refresh), so it doesn't necessarily indicate whether an error had occurred. It's more of a log statement used for debugging than an indication of an error.

It sounds like the main issue you're having is the target poller thread is blocking the main thread from exiting. If this is the only issue, it may indeed be that it's not set as a Daemon thread, which is a bug on the SDK to be addressed.

**Comment by bendog** [comment]
the traces will show up when sampling is true, however, the script will lock up and hence cause my whole system to lock up, as the script is running as a handler a service (`smstools`) and that service is waiting for the script to exit before progressing to the next message.

I think once this bug is resolved it should be fine.

**Comment by chanchiem** [comment]
Issue has been fixed! Will be added to the next release. Thanks for reporting the issue :)

**Comment by chanchiem** [comment]
The patch release has been pushed, so this change is now live on version 2.4.2! :)
