### ISSUE TITLE
urllib[3] not being patched in AWS lambda/python3.6?

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-xray-sdk-python#149]
Hi, is python3 urllib / urllib3 not being patched? I'd greatly like to avoid using 3rd party bloated libraries for https calls.  I tried urllib, urllib3, and requests, and only requests seems to be traced.

**Comment by chanchiem** [comment]
It looks like `patch_all()` might be broken with urllib/httplib. For the time being, I would recommend manually patching urllib/httplib by calling the following method:
```
from aws_xray_sdk.core import patch
patch(('httplib',))
```

Let me know if this fixes it for you. We'll investigate the issue further for the time being

**Comment by kjpgit** [comment]
It's working with patch().  Thanks.

**Comment by chanchiem** [comment]
Hey, if you want to track what Boto is doing as well, you may also patch it. But keep in mind that you will see multiple subsegments that represent both Boto and Boto's underlying httplib call.

This is something that's in the works in order to provide a better customer experience.

I'm closing this for now since the main issue has been resolved. Feel free to open it back up if you have any other issues pertaining to this.

**Comment by ikben** [comment]
Can we repoen this as a documentation issue? A note about it like about how you use x-ray with django might make a big difference
