### ISSUE TITLE
X-RAY creates new session with hardcoded region

### ISSUE THREAD

**Issue by polamayster** [aws/aws-xray-sdk-python#167]
There is probably a reason why new session is created with specific region us-west-2 (is X-Ray available only in this region?):
```python
def _create_xray_client(self, ip='127.0.0.1', port='2000'):
    session = botocore.session.get_session()
    url = 'http://%s:%s' % (ip, port)
    return session.create_client('xray', endpoint_url=url,
                                 region_name='us-west-2',
                                 config=Config(signature_version=UNSIGNED)
                                 )
```
but can it be changed to:
```python
boto3.client('xray',...)
```
so existing default boto3 session could be reused under the hood?
Usecase: application using IAM role to not throttle on call to `/v2/credentials/` in each process/worker when those credentials were already retrieved and stored in session?
If so, I can create MR with a change.

**Comment by chanchiem** [comment]
Hey polamayster,

The X-Ray client here is only used to obtain the Sampling Rules and Targets for centralized sampling. It communicates with the local X-Ray Daemon in order to fetch this, rather than the actual service endpoint itself (the Daemon is responsible for fetching this data). The region here should not affect communications with the Daemon, so we should safely be able to remove the hard coded region without any issues.

As a sanity check, I will test this locally and confirm that the sampling pollers function correctly after removing the region.

**Comment by polamayster** [comment]
Hi chanchiem!

Thanks for a response.
Actually region is just a tip of the iceberg, that catched our attention.
Quick question: can
```python
def _create_xray_client(self, ip='127.0.0.1', port='2000'):
    session = botocore.session.get_session()
    url = 'http://%s:%s' % (ip, port)
    return session.create_client('xray', endpoint_url=url,
                                 region_name='us-west-2',
                                 config=Config(signature_version=UNSIGNED)
                                 )
```
be changed to:
```python
def _create_xray_client(self, ip='127.0.0.1', port='2000', region='us-west-2'):
    url = 'http://%s:%s' % (ip, port)
    return boto3.client('xray', endpoint_url=url,
                        region_name=region,
                        config=Config(signature_version=UNSIGNED)
                        )
```
explanation:
Turned out the real problem we faced is that `_create_xray_client(self, ip='127.0.0.1', port='2000')` is creating new session by calling `session = botocore.session.get_session()` which in turns does `return Session(env_vars)` and created client tries to get credentials from `/v2/credentials/` for IAM role and when it is done in many gunicorn workers inside many docker containers running on ECS repeatedly results in throttling - 429 response code (we can't do gunicorn's preload_app() as it is not compatible with worker_class = 'gevent').
Just wondering why x-ray client needs separate session, why can't it reuse existing session by calling `boto3.client('xray', ...)` which does `return _get_default_session().client(*args, **kwargs)`?
To overcome throttling by x-ray client trying to create session and grab credentials for IAM role in each worker we did something like this:
```python
credentials_provider = ContainerProvider()
session = get_session()
session._credentials = credentials_provider.load()  # RefreshableCredentials
boto3.setup_default_session(botocore_session=session)
# monkey patch botocore session to always return existing session with credentials and not new one each time (x-ray)
botocore.session.get_session = lambda: session
```

**Comment by chanchiem** [comment]
Hey Polamayster,

How are these X-Ray clients being generated multiple times in your application? We had designed this client to only be created once upon each poller thread: the rule poller and target poller, so in the life cycle of each application, my concern is that if your workers are invoking new clients over and over, if using a default session would alleviate this.

We don't see an issue with re-using a default session, but there is one issue. Our SDK uses `botocore` as a dependency rather than `boto3`, so we'd ideally want a solution that can be accomplished in `botocore`. It looks like the default session is something that's implemented [outside](https://github.com/boto/boto3/blob/develop/boto3/__init__.py#L27) `botocore` in `boto3`.

Since the issue you're having is related to credential gathering, and our client doesn't use credentials (this part is handled by our Daemon), I wonder if a possible solution would be to predefine the credentials to a null value.

**Comment by polamayster** [comment]
Hi chanchiem,

Thanks a lot for your comment! I will give your solution a try. Concern about `boto3` dependency is understood.

**Comment by polamayster** [comment]
Hi chanchiem,

Sorry for long silence, I finally got a chance to test your solution with `aws_access_key_id='', aws_secret_access_key=''` and looks like it works fine, so I can't see `credentials = self.get_credentials()` calls in logs originated from aws_xray_sdk anymore.
Would you consider to make `aws_access_key_id='', aws_secret_access_key=''` change in aws-xray-sdk-python or should I open a MR with your fix and some tests?

Thanks a lot once again!

**Comment by chanchiem** [comment]
We would gladly accept PRs!

Glad the solution worked out for you!

Thanks,
Chan Chiem Jeffery Saeteurn

**Comment by polamayster** [comment]
Side note: I was adding a fix and associated tests and turned out this issue is reproducible if `botocore` version `< 1.12.68` (fix: https://github.com/boto/botocore/commit/90ed2deadd9f8f64a3ba115b4c546019a89ef79e, https://github.com/boto/botocore/blob/90ed2deadd9f8f64a3ba115b4c546019a89ef79e/botocore/session.py#L812:L813 in particular) and as https://github.com/aws/aws-xray-sdk-python/blob/ab1327e9ae858c4132619854a84019414b7b18e2/setup.py#L49 it affects `aws-xray-sdk-python` clients with `botocore` version in this range.

So proposed fix if still relevant/appropriate regarding `aws-xray-sdk-python` vs `botocore` would be guarding against unnecessary credentials retrieval for clients with older versions of `botocore`.

@chanchiem, @haotianw465(https://github.com/aws/aws-xray-sdk-python/blame/master/aws_xray_sdk/core/sampling/connector.py#L163) what do you think?

**Comment by polamayster** [comment]
So should fix still be implemented or issue closed with botocore version upgrade as a fix?

**Comment by polamayster** [comment]
Let me reiterate, because looks like I wasn't clear in explanation:
`botocore` starting version `1.12.68` does not require credentials for a client with `config=Config(signature_version=UNSIGNED)`: https://github.com/boto/botocore/commit/90ed2deadd9f8f64a3ba115b4c546019a89ef79e#diff-29bf4883de496fd71c0deda976cc480fR812
```python
if config is not None and config.signature_version is UNSIGNED:
    credentials = None
```
and this it used in x-ray-sdk for client creation:
```python
def _create_xray_client(self, ip='127.0.0.1', port='2000', region='us-west-2'):
    url = 'http://%s:%s' % (ip, port)
    return boto3.client('xray', endpoint_url=url,
                        region_name=region,
                        config=Config(signature_version=UNSIGNED)
                        )
```
but as `aws-xray-sdk-python/setup.py` has `botocore>=1.11.3` specified it has no affect for a range of versions that satisfy this requirement (from `1.11.3` to `1.12.67`).
I do not see any breaking changes introduced by newer version of `botocore` neither in changelog, nor by running application with upgraded `botocore` version.

**Comment by chanchiem** [comment]
Thanks for letting us know! I think since we want to be sure we accept the current version range and not constrain our customers to only use up to 1.12.67, we can use the solution of manually setting the credentials to an empty string: `aws_access_key_id='', aws_secret_access_key=''`

Can you confirm that it worked for versions less than as well as greater than and equal to `1.12.68`?

**Comment by polamayster** [comment]
Yes, credentials set to empty strings worked for `botocore` versions below and above `1.12.68`.
Thanks on update, I will add a fix and tests shortly.

**Comment by polamayster** [comment]
tests fail due to #179
