### ISSUE TITLE
Subsegment name serialization causing MissingName error

### ISSUE THREAD

**Issue by Jacob-Doetsch** [aws/aws-xray-sdk-python#168]
XRay Daemon reports the following error:
```bash
xray-daemon_1  | 2019-07-28T17:35:30Z [Info] Successfully sent batch of 1 segments (0.481 seconds)
xray-daemon_1  | 2019-07-28T17:35:30Z [Error] Unprocessed segment: {
xray-daemon_1  |   ErrorCode: "MissingName",
xray-daemon_1  |   Id: "3bdcccc4799c57fa",
xray-daemon_1  |   Message: "Invalid subsegment. ErrorCode: MissingName, Cause: null"
xray-daemon_1  | }
xray-daemon_1  | 2019-07-28T17:35:30Z [Warn] Batch that contains unprocessed segments
```

Simple setup. Django app, using middleware. setup includes:
```python
XRAY_RECORDER = {
    'AWS_XRAY_DAEMON_ADDRESS': 'xray-daemon:2000',
    'AWS_XRAY_TRACING_NAME': 'TheNextBigThing',
    'AWS_XRAY_CONTEXT_MISSING': 'LOG_ERROR'
}

INSTALLED_APPS = [
    ...
    'aws_xray_sdk.ext.django',
]

MIDDLEWARE = [
    'aws_xray_sdk.ext.django.middleware.XRayMiddleware',
    ...
]
```

I think subsegments' subsegments' names are not being serialized correctly. Below is a snippet from the XRay Daemon payload.Notice the `"name": {"py/newargs": ["core/snippets/ga.html"]}` name of the subsegment, which should instead be a string according to the segment JSON schema.

```json
    ...
    "subsegments": [
        {
            ...
            "in_progress": false,
            "name": "account/login.html",
            "namespace": "local",
            "parent_id": "c572ac3f20a195dc",
            "subsegments": [
                {
                    "id": "69ef19799fec25ba",
                    "in_progress": false,
                    "name": {
                        "py/newargs": [
                            "core/snippets/ga.html"
                        ]
                    },
                    "namespace": "local",
                    "parent_id": "5ecd89473a50fa17",
                    "type": "subsegment"
                },
                ...
            ]
            ...
        }        
```

All SDK versions between 2.0.1 and 2.4.2 were tested and have the same issue. Same issue on Python 3.6 and 3.7 as well. Django version is 2.2.3.

**Comment by chanchiem** [comment]
Hey,

What framework are you instrumenting that's generating the subsegments? The Django Middleware is instrumented to generate Segments only. It seems like whatever's generating the subsegment is where the issue is. Is there a code snippet you can provide that pinpoints what method call within your application is causing this?

Additionally, what environment are you running this in?

**Comment by chanchiem** [comment]
Hmmm interesting, it looks like the issue you're having is exactly the same. @crustafari, can you provide your minimal X-Ray configuration information? I can't seem to reproduce this issue on my end.

Also, what environment are you running this in? Is this in Lambda? If this is in a regular desktop environment, this confuses me because Django should be generating segments, not subsegments. It only generates subsegments if you're using a Serverless architecture (API Gateway -> Lambda).

**Comment by Jacob-Doetsch** [comment]
My environment is a Django 2.2.3 app in a Docker container running locally, with the xray daemon running in a separate container.

**Comment by chanchiem** [comment]
We don't currently support versions of Django > 2 yet. It's in our backlog to add support for it as it has been a customer ask #10. Which probably makes sense why we're seeing these errors. There has probably been some major changes to Django that has caused it to not work with our current Django patcher. A PR is always welcome and we could provide guidance. In the mean time please stay tuned.
