### ISSUE TITLE
Supported Python Libraries - Is psycopg2 supported?

### ISSUE THREAD

**Issue by tim-pugh** [aws/aws-xray-sdk-python#225]
one these site, it shows the supported python libs for x-ray: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python.html
https://docs.aws.amazon.com/xray-sdk-for-python/latest/reference/

But I found a PR for psycopg2 that seems to indicate it may be supported as well: https://github.com/aws/aws-xray-sdk-python/issues/80

looking at the source code, seems to me like it may be: https://github.com/aws/aws-xray-sdk-python/tree/master/tests/ext

Q1.) Is psycopg2 supported?
Q2.) Is there a system in place for updating docs? Maybe a tag that can used to assist keeping track of new additions?

**Comment by bhautikpip** [comment]
Hi @tim-pugh ,

Thanks for opening this issue. Yes psycopg2 is supported. I will update this support in docs. In order to mitigate docs update issue in future I will create a new label like aws-docs-update to remind to update the docs as we merged the PR for new support features. Also, it will help tracking docs updates with PR. Thanks for the suggestion.

**Comment by NathanielRN** [comment]
Closed in #266
