### ISSUE TITLE
Support httpx/httpcore

### ISSUE THREAD

**Issue by smcoll** [aws/aws-xray-sdk-python#248]
i'd be interested in seeing support for [`httpx`](https://www.python-httpx.org/) alongside `aiohttp`, `httplib`, and `requests`.  The default transport layer for `httpx` is [`httpcore`](https://www.encode.io/httpcore/) which supports HTTP/2 in addition to HTTP/1.1.

These libraries have async support for `asyncio`, `trio`, and `curio`.

**Comment by srprash** [comment]
Hi @smcoll Thanks for opening this feature request. I'll put this in our backlog and would work on it as soon as possible. We would highly appreciate if you want to contribute towards the `httpx` support in the SDK. :)

I would also recommend you to try and open this request on the [OpenTelemetry for Python](https://github.com/open-telemetry/opentelemetry-python) since it already has a wide array of growing [instrumentation](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/master/instrumentation) support and also active contribution from the open source community. We are also actively working to provide X-Ray support for customers using OpenTelemetry Python.

**Comment by smcoll** [comment]
Cool - i added issue https://github.com/open-telemetry/opentelemetry-python-contrib/issues/263

**Comment by thehesiod** [comment]
this xray dinosaur has awoken from his slumber :) We just swapped to async APIs and I need it for aiohttp client tracing to figure something out so I'll be working on support, I am responsible for the ddtrace aiohttp client impl so I should be able to get 'er done shortly :)

**Comment by thehesiod** [comment]
btw for others that want to enable it globally I'm doing something like this (note untested):

```python
def _wrap_clientsession_init(func, instance, args, kwargs):
    trace_config = aws_xray_trace_config()
    kwargs['trace_configs'] = [trace_config]
    return func(*args, **kwargs)

wrapt.wrap_function_wrapper(aiohttp, "ClientSession.__init__", _wrap_clientsession_init)
```
