### ISSUE TITLE
Aiohttp improvements, feedback wanted

### ISSUE THREAD

**Issue by pfreixes** [aws/aws-xray-sdk-python#28]
Hi folks,

I'm thinking in work on a pair of PR to improve the functionality of AWS-XRay for the Aiohttp framework.

First of all, I would like to add a new `TraceConfig` object - the new Aiohttp Client tracing system since 3.0 [1] - that will allow users just make something like that to inject the specific headers:

```python
import aiohttp

from aws_xray_sdk.ext.aiohttp.client import TraceConfig

async with aiohttp.ClientSession(trace_configs=[TraceConfig()]) as client:
    await client.get('http://example.com/some/redirect/')
```

My main concern with that is how to deal with different Aiohttp versions, is there any requirement or advice with that? 

Second, I would like to deprecate - remove? - the current middleware implementation that uses a deprecated pattern since the 2.X version, we strongly recommend the new one  [2], any concerns?.

[1] https://docs.aiohttp.org/en/stable/client_advanced.html#client-tracing
[2] https://docs.aiohttp.org/en/stable/web_advanced.html?highlight=middleware#middlewares

**Comment by haotianw465** [comment]
Hi, in general the current functionality the SDK already supports for 2.x should remain functioning. Since 3.0 is released on this month, I would assume it takes some time for most of the aiohttp users to upgrade to 3.x.

But to be more specific, support of `aiohttp` includes two parts: middleware and client. The SDK right now only provides a `aiohttp` middleware but it doesn't provide patch code for the client. So you can implement a whole 3.x support with new middleware, client/config, or you can just do the client/config and stick with the 2.x middleware for a while.

For `TraceConfig` I think the naming is too general if your intention is just to carry enough information to inject trace header to the outbound http call. Could you check module [TraceHeader](https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/models/trace_header.py) to see if it fits your needs? 

Also for client support it involves two things: one is to inject trace header to the call, the other is to capture this call as a subsegment. You can check the `requests` patcher to see how a call made via `requests` is captured and at the meantime has trace header injected: https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/requests/patch.py

Please let me know your thoughts and I'm happy to review your PR and merge it as soon as possible.

**Comment by haotianw465** [comment]
Close this since I believe we reached an agreement for doing client support only for 3.x for now.
