### ISSUE TITLE
What information does Flask-SQLAlchemy send?

### ISSUE THREAD

**Issue by harveyslash** [aws/aws-xray-sdk-python#33]
I would like to get the actual queries that are being executed along with the time it took to execute them. 

Right now the most informative text that I can see is 
`sqlalchemy.orm.query.one` (indicating that i performed a one() query) 

Is there any way to get actual sql query data , or the queries itself ?

**Comment by haotianw465** [comment]
The actual query string capture was originally in the PR submitted by @therealryanbonham, but we requested that part of logic to be removed and submitted with a separate PR. 

The actual query might contain sensitive user information and we will have to require the query capture PR to be sanitized and reviewed by our security team to make sure no sensitive user data can sneak into the captured data.

We haven't receive the separate PR yet but I will ping @therealryanbonham to check if there is any recent plan on the query capture.

**Comment by harveyslash** [comment]
can you link me to that PR ? 
I dont mind having some sensitive information being sent. 
I would like to see if I can use X ray for my application right now.

**Comment by haotianw465** [comment]
Yes sorry I forget to put that link on. https://github.com/aws/aws-xray-sdk-python/pull/14

**Comment by haotianw465** [comment]
Hi @harveyslash just want to let you know that the PR for query capture is submitted: https://github.com/aws/aws-xray-sdk-python/pull/34. Please feel free to try it out and provide any feedback under that PR.

**Comment by harveyslash** [comment]
I installed that using: 
pip install --upgrade git+https://github.com/therealryanbonham/aws-xray-sdk-python.git

And it doesnt seem to have changed anything. 

I am not getting the actual query in my X-ray console

**Comment by therealryanbonham** [comment]
You need to include the branch..

git+https://github.com/therealryanbonham/aws-xray-sdk-python.git@sqlalchemy_query#egg=aws-xray-sdk

**Comment by harveyslash** [comment]
just tried the branch, now im getting : 

> File "venv/beatest-flask-rest-backend-36/lib/python3.6/site-packages/aws_xray_sdk/core/emitters/udp_emitter.py", line 55, in _send_data
>     self._port))
> OSError: [Errno 40] Message too long

And my X-ray console doesnt show the requests that had the message too long error. 
I about 15 fields in my table, so the sql query could be fairly long

**Comment by haotianw465** [comment]
The default UDP packet size is usually 64KB but it might vary on different OS. You can consider to increase this limit.

You can also change `streaming_threshold` to a lower value so that some data is streamed out earlier:
`xray_recorder.configure(streaming_threshold=10)`

See https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/recorder.py#L118. The default value is 30 which means a segment will stream out its children subsegments when the total children count reaches 30. You can change to 10 or even lower to fit your use case.

**Comment by haotianw465** [comment]
Since the PR for query capture is already out https://github.com/aws/aws-xray-sdk-python/pull/34, I will close this in favor of the PR to make sure we have a single place to track feedback, concerns and progress regarding this new feature.

If you have other questions regarding the SDK usage in general, feel free to post on our forum https://forums.aws.amazon.com/forum.jspa?forumID=241 or open new issues. But feel free to leave any comments here if you still have concerns.
