### ISSUE TITLE
Provide `IGNORE` option for `AWS_XRAY_CONTEXT_MISSING` configuration variable

### ISSUE THREAD

**Issue by NathanielRN** [aws/aws-xray-sdk-python#334]
### Description

In #52, it was noted that calls to unsupported APIs will result in exceptions that break a customer's app. We suggested a workaround where setting `AWS_XRAY_CONTEXT_MISSING=LOG_ERROR` logs instead of throwing an exception as explained in our [X-Ray Java SDK Documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html).

However, there are so many logs that the log file is flooded.

We should update the code to support an option like `IGNORE` so that neither an exception is raised nor a log message is printed out. (Or we can log at a `Debug` log level with `LOG_DEBUG`).

Perhaps we can even make it only log once so that the customer can still notice the issue.

https://github.com/aws/aws-xray-sdk-python/blob/f5f9c470b189bb34f31a1d0a28f497741132b7d2/aws_xray_sdk/core/context.py#L122-L125

**Comment by eercanayar** [comment]
Thanks @NathanielRN for your bias for action! 🚀 I would vote for the `IGNORE` option to silence all missing segment logs, even without logging once; because of following reasons:

- The setting `AWS_XRAY_CONTEXT_MISSING` = `IGNORE` is not default, so the user will take action to set it `IGNORE`, so it's an informed decision.
- If the traced resource is a short-lived function and uses a function with a missing context just once, it'll produce the same amount of logs since the first occurrence will be logged.

**Comment by willarmiros** [comment]
Thank you for raising this request! We will prioritize it as soon as we can, but would also be open to a PR to add support for this. It should be fairly straightforward to add - just be sure to document in README!
