### ISSUE TITLE
No exception information for PynamoDB integration

### ISSUE THREAD

**Issue by Dunedan** [aws/aws-xray-sdk-python#35]
Currently the PynamoDB integration doesn't provide stack traces for failed requests to DynamoDB. The reason is pretty simple: As `requests` needs to be patched for it, there simply is no exception yet, when the response is processed for X-Ray, as the PynamoDB code wasn't called yet.

Any idea what'd be the best way to handle that?

**Comment by haotianw465** [comment]
You can use `@xray_recorder.capture()`  to annotate `PynamoDB` call. The decorator will automatically create a top level subsegment and record whatever exception thrown from `PynamoDB` client. See https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/recorder.py#L317 which does the heavy lifting for the decorator.

This is not ideal since the stack trace is not in the same subsegment as the actual http status code, API parameters, endpoint etc. But it will at least be present on the parent of the actual call subsegment. 

But this also makes sense as the `PynamoDB` client call reflects a logical operation that might not tied to any individual outgoing http request. In another word, the exception thrown by the client is determined by the aggregated results from lower level details.

Please let me know your thoughts.

**Comment by haotianw465** [comment]
Hi, any update? You get it working properly or need additional help?

**Comment by Dunedan** [comment]
Sorry, for the late response, but I haven't had time yet to further look into it. It also looks like I won't have any time in the near future, especially as we have so few exceptions where we would benefit from it, that it's not at the top of our priorities right now.

**Comment by haotianw465** [comment]
No problem. I'm closing this for now. Whenever you have time to look at this issue again, see if the suggestions work for you and feel free to comment here to continue the conversation.
