### ISSUE TITLE
can set something to avoid Message too long

### ISSUE THREAD

**Issue by Liubey** [aws/aws-xray-sdk-python#351]
udp_emitter.py", line 63, in _send_data
    self._port))
error: [Errno 40] Message too long

May be my segment is too many of mysql segment,Can I set something to force upload this segments?

**Comment by Liubey** [comment]
streaming_threshold=0 or     streaming_threshold=100000 is not working

**Comment by wangzlei** [comment]
A segment might contains a group of child subsegments, causes the total size is over the UDP limit. In this case we can enhance the streaming strategy as in https://github.com/aws/aws-xray-sdk-java/pull/344

Before that, could you confirm the issue is not caused by low MTU setting? https://stackoverflow.com/questions/900697/how-to-find-the-largest-udp-packet-i-can-send-without-fragmenting

**Comment by Liubey** [comment]
@wangzlei Is your comment "streaming strategy as in https://github.com/aws/aws-xray-sdk-java/pull/344" will transplant to python sdk？

**Comment by wangzlei** [comment]
> @wangzlei Is your comment "streaming strategy as in [aws/aws-xray-sdk-java#344](https://github.com/aws/aws-xray-sdk-java/pull/344)" will transplant to python sdk？

Yes, this is a right way to split the large size segment contains too many subsegments.
