### ISSUE TITLE
aws-xray-sdk-python compatibility with Python 3.12

### ISSUE THREAD

**Issue by Newlevel462** [aws/aws-xray-sdk-python#423]
Hi when I try to deploy my AWS Chalice app to Lambda using Python 3.12 it does not work if aws-xray-sdk is enabled.  I get an error saying 

"[ERROR] Runtime.ImportModuleError: Unable to import module 'app': cannot import name 'formatargspec' from 'inspect' (/var/lang/lib/python3.12/inspect.py)
Traceback (most recent call last):"

If I remove all references to aws-xray-sdk and deploy it works.  Could you let me know if you are going to put out an updated version soon that is compatible with Python 3.12?

**Comment by deepu1014git** [comment]
I have the similar issue with Python 3.11.4.
When I add "**from aws_xray_sdk.core import patch_all**" to my lambda handler, I see below error:

[ERROR] Runtime.ImportModuleError: Unable to import module 'handler': cannot import name 'formatargspec' from 'inspect' (/var/lang/lib/python3.11/inspect.py)

**Comment by mxiamxia** [comment]
It looks `formatargspec` function has been deprecated which is not supported in Python 3.12.
```
DeprecationWarning: formatargspec is deprecated since Python 3.5. Use signature and the Signature object directly
```

**Comment by Newlevel462** [comment]
it looks like aws-xray-sdk uses a package called wrapt which uses formatargspec

I think this is what is causing the error - please could you look into this

**Comment by jj22ee** [comment]
Hello, I've reproduced this error. It looks like this error occurs due to [using wrapt versions < 1.14](https://github.com/imartinez/privateGPT/issues/884).

I've tested that customers error appears using `wrapt==1.13.3` when installing my requirements.txt. I've tested that this error is gone when using `wrapt==1.14` after deleting the previous installation of `wrapt`.

Could you check your `wrapt` version, remove the current version if it is older than 1.14, and upgrade to newer version?

**Comment by Newlevel462** [comment]
unfortunately am still getting the same error when deploying the aws chalice lambda function

**Comment by jj22ee** [comment]
When tested on my end with Chalice, I had to delete all the current downloaded dependencies (including wrapt) and then reinstall with `pip3 install -r requirements.txt -t .` to apply the updated wrapt, else I would still get the previous error. Have you tried deleting previous version of wrapt in your Lambda?

**Comment by Newlevel462** [comment]
yes

**Comment by jj22ee** [comment]
My repro steps:

Followed guide in https://github.com/aws/chalice?tab=readme-ov-file#quickstart until `Deploying` section.
- `python3.12 -m ensurepip --upgrade` -> `installed pip-23.2.1`
- `python --version` -> `Python 3.12.1`
- `requirements.txt` includes:
```
chalice==1.31.0
aws-xray-sdk==2.12.0
wrapt==1.16
```
- Modified `app.py` to include:
```
import json
from chalice import Chalice
from aws_xray_sdk.core import patch_all, xray_recorder
```
- Ran:
```
pip3 install -r requirements.txt -t .
chalice deploy
```
- Lambda confirmed to use Python 12 and executes with no error.

With this setup, I cannot reproduce issue. Changing `wrapt` version to `1.13.3` will reproduce the error, but then deleting all vendored dependencies and then removing `wrapt` entirely from requirements.txt will also fix the error when running `chalice deploy`.

------

@Newlevel462 Is there any other info you can provide about your chalice app configuration? Current I assume that the XRay Python SDK is compatible with Python 12 since I was able to get it working with the above repro steps. Possibly there is a configuration issue with the Chalice Application on your end. Perhaps, could you provide pip3 version you are using?

**Comment by Newlevel462** [comment]
thanks it works now
