### ISSUE TITLE
Swallowed `return_value` in `record_subsegment(...)`?

### ISSUE THREAD

**Issue by nelz9999** [aws/aws-xray-sdk-python#43]
My Python may not be super strong, but in my reading of `try: except: finally:`, it seems that the `return_value` is being trashed in the `LOG_ERROR` case.

From https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/recorder.py:
```
        return_value = None

        try:
            return_value = wrapped(*args, **kwargs)
            return return_value
        except Exception as e:
            exception = e
            stack = traceback.extract_stack(limit=self._max_trace_back)
            raise
        finally:
            # No-op if subsegment is `None` due to `LOG_ERROR`.
            if subsegment is None:
                return
```

Isn't that last `return` actually equivalent to `return None`?

**Comment by haotianw465** [comment]
You are absolutely right. It should be 

```python
        return_value = None

        try:
            return_value = wrapped(*args, **kwargs)
            return return_value
        except Exception as e:
            exception = e
            stack = traceback.extract_stack(limit=self._max_trace_back)
            raise
        finally:
            # No-op if subsegment is `None` due to `LOG_ERROR`.
            if subsegment is None:
                return return_value
```

We have a unit test cover this scenario but unfortunately that unit test fails to check the return value. See https://github.com/aws/aws-xray-sdk-python/blob/master/tests/ext/botocore/test_botocore.py#L107.

Feel free to submit a PR and I can merge it as soon as possible. But regardless we will make sure this will be fixed in the next release.
